### ISSUE TITLE
画图表不工作了

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/covid19-eu-zh.github.io#3]
@neoatlantis 应该是由于数据文件格式更新了

**Comment by emptymalei** [comment]
奥地利的网页更新了，所以之前有 bug，修的时候顺便[新增了](https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/covid-19-at.csv)

recovered | deaths
-- | --


德国[新增了](https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/covid-19-de.csv) deaths，不知道有没有影响。

**Comment by cmp0xff** [comment]
我這是不能生成圖的。等 @neoatlantis 來看看

**Comment by neoatlantis** [comment]
修好了，是因为我一开始犯懒没有考虑CSV的Header……（
